-- General information
Simulation {
    name        = 'Modelo', 
    description = 'Generated by GiD2GeMA' 
} 

-- Auxiliary files 
dofile('$SIMULATIONDIR/$SIMULATIONNAME_model.lua') 
dofile('$SIMULATIONDIR/$SIMULATIONNAME_solution.lua') 

-- Generated by Abaqus2GeMA v0.1.0