-------------------------------------------------------------
--  Numerical Solvers
-------------------------------------------------------------
NumericalSolver {
    id          = 'solver',
    typeName    = 'ArmadilloSolver',
    description = 'Direct matrix solver',
}

-------------------------------------------------------------
--  Physical Methods
-------------------------------------------------------------
PhysicalMethod {
    id       = 'Step1',
    typeName = 'MechanicalFemPhysics.PlaneStrain',
    type     = 'fem',
    mesh     = 'mesh',
    ruleSet  = 1,

    elementGroups      = { 'Formacao_Quadrilateral','Gravel_Quadrilateral','Tela_Quadrilateral', },
    materials          = { 'mohrCoulomb','vonMises', },
    boundaryConditions = { 'dispInitial','pEdgesStep1', },
    properties         = { material = 'Mec_material' }
}

PhysicalMethod {
    id       = 'Step2',
    typeName = 'MechanicalFemPhysics.PlaneStrain',
    type     = 'fem',
    mesh     = 'mesh',
    ruleSet  = 1,

    elementGroups      = { 'Formacao_Quadrilateral','Gravel_Quadrilateral','Tela_Quadrilateral', },
    materials          = { 'mohrCoulomb','vonMises', },
    boundaryConditions = { 'dispStep2','pEdgesStep2', },
    properties         = { material = 'Mec_material' }
}

dofile('$SIMULATIONDIR/AuxData.lua')

-------------------------------------------------------------
--  Solver options
-------------------------------------------------------------
local solverOpitionsStep1 = {
  type               = 'transient nonlinear'
  timeMax            =  6.,
  timeInitIncrement  = 2.,
  timeMinIncrement   =  2.,
  timeMaxIncrement   =  4.,
  iterationsMax      = 100,
  eulerTheta         = 1.000E+00,
  attemptMax         = 10,  
  tolerance          ={mechanic =1.000E-05,},
  newtonRaphsonMode      = 'full',
  Increment_Time_Factor = 2,
  Frequency = 1,
}

local solverOpitionsStep2 = {
  type               = 'transient nonlinear'
  timeMax            =  102.,
  timeInitIncrement  = 4.,
  timeMinIncrement   =  1e-40,
  timeMaxIncrement   =  13.,
  iterationsMax      = 100,
  eulerTheta         = 1.000E+00,
  attemptMax         = 10,  
  tolerance          ={mechanic =1.000E-05,},
  newtonRaphsonMode      = 'full',
  Increment_Time_Factor = 2,
  Frequency = 1,
}

-- Generated by Abaqus2GeMA v0.1.0