-------------------------------------------------------------
--  Numerical Solvers
-------------------------------------------------------------
NumericalSolver {
    id          = 'solver',
    typeName    = 'ArmadilloSolver',
    description = 'Direct matrix solver',
}

-------------------------------------------------------------
--  Physical Methods
-------------------------------------------------------------
PhysicalMethod {
    id       = 'Step2',
    typeName = 'MechanicalFemPhysics.PlaneStress',
    type     = 'fem',
    mesh     = 'mesh',
    ruleSet  = 1,

    elementGroups      = { 'Material1_Quadrilateral','Material2_Quadrilateral', },
    materials          = { 'mohrCoulomb','elastic', },
    boundaryConditions = { 'dispStep2','cloadStep2','pEdgesStep2', },
    properties         = { material = 'Mec_material' }
}

-- Generated by Abaqus2GeMA v0.1.0