#include "printers_lua.h"

void printersLua::printHeaderLua(std::ofstream& out)
{
 if (out.is_open())
 {
  out << "-- General information" << std::endl;
  out << "Simulation {" << std::endl;
  out << "    name        = 'Modelo', " << std::endl;
  out << "    description = 'Generated by GiD2GeMA' " << std::endl;
  out << "} " << std::endl;
  out << std::endl;
  out << "-- Auxiliary files " << std::endl;
  out << "dofile('$SIMULATIONDIR/$SIMULATIONNAME_model.lua') " << std::endl;
  out << "dofile('$SIMULATIONDIR/$SIMULATIONNAME_solution.lua') " << std::endl;
  out << std::endl;
 }
}
